name: car_e_commerce
description: Cars E-Commerce App to see all cars news 

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  # icons
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.0.0

  # bloc
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1

  # for good operation
  equatable: ^2.0.3
  flow_builder: ^0.0.6
  catcher: ^0.6.9

  # firebase
  firebase_auth: ^3.3.11
  firebase_core: ^1.13.1
  cloud_firestore: ^3.1.10
  firebase_database: ^9.0.8
  firebase_crashlytics: ^2.5.3

  # Login methods
  google_sign_in: ^5.2.4

  # Starting
  flutter_native_splash: ^2.1.1

  # widgets
  fluttertoast: ^8.0.9
  flutter_svg: ^1.0.3

  # data operations
  shared_preferences: ^2.0.13
  sqflite: ^2.0.2

  # on boarding
  liquid_swipe: ^2.1.1
  google_fonts: ^2.3.1
  flutter_screenutil: ^5.3.1
  material_floating_search_bar: ^0.3.7
  widget_mask: ^1.0.0+0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/OnBoarding/
     - assets/images/Logo/
     - assets/icons/
     - assets/mask/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
